name: 'Duplicate Issue'

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: 'duplicate'
          issue-comment: >
            This report has been marked as a duplicate. Please link the existing report so readers can follow it and add relevant reproduction details there. This conversation remains unlocked.
          close-issue: true
          lock-issue: false
